<?php

namespace Shooter\InterfaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BeverageDrinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeverageDrinkRepository extends EntityRepository
{
}
