<?php

namespace Shooter\InterfaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DrinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrinkRepository extends EntityRepository
{
}
